### ISSUE TITLE
[Feature Request] Implement `--no-cache` option

### ISSUE THREAD

**Issue by gilescope** [rami3l/pacaptr#1]
There’s a lot of random flags in package managers you have to set in docker to say please don’t cache this package which is important in docker to keep image sizes small.

Would be great to abstract this away behind a -no_cache flag or similar...

**Comment by rami3l** [comment]
Thanks a lot for your feedback!

I’m not quite sure what you’re trying to say though. Correct me if I’m wrong: you want an option that resembles doing first `-S` and then `-Scc`, but all in one command?

PS: Just in case, as for now you also have a workaround by just passing the flag to `apk` for example, via `pacaptr -S <pack> -- --no-cache`.

**Comment by rami3l** [comment]
Also, I understand that adding a prompt to package managers like `apk` might be problematical. So now we have the `--no-confirm` option to override that, and when I have time I’ll try to add config file support, after which you should be able to disable the prompt permanently if you don’t like it. 🤔

**Comment by rami3l** [comment]
@gilescope I added a simple fix in ebb68f3, which reuses the `--no-cache` flag in `apk`, whereas in `dpkg` and `brew` I think it's fine to just do `-S` and then `-Scc` consecutively.I haven't used this program in docker though, so I cannot really know if that's exactly what you wanted.

**Comment by gilescope** [comment]
Exactly, on alpine it's this kind of thing:
apk add --no-cache

Looks like on other package mangers you have to call clean after
you've installed

the things you want to install.

**Comment by rami3l** [comment]
@gilescope Then this issue should be closed by ebb68f3. Feel free to comment if you encounter any problem.
