### ISSUE TITLE
[Request] Precompiled Binary for Apple Silicon

### ISSUE THREAD

**Issue by luxus** [rami3l/pacaptr#103]
hello,
I just found out about this tool and tried it on my Mac m1
the brew install doesn't install a arm64 version and is not usable because it will try to run brew in rosetta2
is it possible to add a arm64 version?
I was able to compile it from git source, but it would be easier to do it with brew

**Comment by rami3l** [comment]
Thanks for your advice! 

Sorry for the inconvenience, but since this project is tested and compiled using GitHub Actions, which doesn't support ARM Macs (yet), it's still impossible to simply add an ARM macOS binary in the release. However, I'm willing to do exactly that once it can be easily done.

I sadly don't have an ARM Mac to test with, but it's really nice to know that `pacaptr` is working for you :)

**Comment by luxus** [comment]
thanks for answering so quickly.. i wonder why so many other terminal tools have a arm version in brew.

**Comment by rami3l** [comment]
@luxus I think that's because Homebrew officially owns some M1 machines to compile bottles in ARM, but that's not generally possible for formulae in non-official taps right now.

**Comment by rami3l** [comment]
@luxus It turns out that we might be able to cross-compile for Apple Silicon once GitHub Actions official x64 instances get their Big Sur update. However this is currently blocked by
https://github.com/actions/virtual-environments/issues/2486.

**Comment by rami3l** [comment]
@luxus I made a test build in [`v0.12.0-TEST002`](https://github.com/rami3l/pacaptr/releases/tag/v0.12.0-TEST002). Would you mind testing for me if [`pacaptr-macos-universal`](https://github.com/rami3l/pacaptr/releases/download/v0.12.0-TEST002/pacaptr-macos-universal.tar.gz) works on your M1 machine as expected?

Warning: A security alert might pop up. Let's see if you can get rid of it by going to `System Preferences -> Security & Privacy -> General`.

![Security Alert](https://user-images.githubusercontent.com/33851577/121752297-2411e580-cb10-11eb-9aa4-bdb4997bd2a8.jpg)

**Comment by luxus** [comment]
it works... thanks for handling  all the trouble I got you with this request 
I didn't get the popup.. it can be fixed by secondary click and "open" as well if I remember correctly
