### ISSUE TITLE
[Feature Request] Support for Gentoo/Portage

### ISSUE THREAD

**Issue by daemonspudguy** [rami3l/pacaptr#108]
The BASH version had it, and I would like for the Rust version to support Portage as well.

**Comment by rami3l** [comment]
@daemonspudguy Thanks for your suggestion!

Experimental support has been added in ab21fc9, check it out!

PS: Sadly, I don't use Gentoo personally, so the implementation might not be accurate enough. Please feel free to ask me anything!
