### ISSUE TITLE
[Feature Request] MacPorts support maybe?

### ISSUE THREAD

**Issue by Finermeerkat137** [rami3l/pacaptr#18]
I personally don't use homebrew, but I use MacPorts. I do miss `pacman`'s syntax though, so would it be possible to add MacPorts as well?

**Comment by rami3l** [comment]
@Finermeerkat137 Roger! I will get myself working on this issue very soon.

It should be simple in the first place to get the basic support by porting logic from the original project, but may I know about your opinion on the following?
- Should my `macports` support contain some sort of "prompt", as shown in the image attach to the repo's README? (AFAIK `ports` doesn't come with any sort of prompt, does it?)
- Should `pacaptr` include automatic `sudo` invocation while not running as root?

**Comment by rami3l** [comment]
@Finermeerkat137 Anyway, I made my first attempt in 5f99620. Would you mind checking out my progress and giving me some feedback? :D

**Comment by Finermeerkat137** [comment]
Sorry, I was a bit busy and couldn't get back to you :( Your macports implementation is golden!  It might be a good idea to have a prompt, as you're right, MacPorts doesn't have one built in. If possible, maybe pacaptr should automatically escalate to root only for operations that require it (pacman -S in apt for example, but not pacman -S in brew). Would that work?

**Comment by rami3l** [comment]
@Finermeerkat137 Thanks for your comments! This issue should now be closed.

Please feel free to comment if you encounter any problem.
