### ISSUE TITLE
[Feature Request] Proper `sudo` invocation

### ISSUE THREAD

**Issue by rami3l** [rami3l/pacaptr#2]
The current program works fine with `macOS/homerbrew`, but mostly because `brew` is a root-less package manager. When working with `Debian/apt`, some *big* actions require `sudo` (eg. `-S`) while others don't (eg. `-Si`).

The problem is,  should we implement auto invocation of `sudo` in `pacaptr`, or should we let the users themselves to decide?

If we accept the auto invocation, then we are deviating from the original behavior of `pacapt`, and this might complicate the support of different package managers. So in this case, we have to carefully consider how to implement this feature.

If not, there must be a way of installing `pacaptr` (other than using `Linuxbrew` and `cargo install`) so that it can be used through `sudo` (`gsudo` in Windows is not the case here). But then there comes another problem: the upcoming `pacaptr.toml` support means that the configuration is user-dependent.

**Comment by rami3l** [comment]
Should be fixed as of 4bed594.

**Comment by AndydeCleyre** [comment]
Is it possible to override the command used, to for example use `doas` instead?

**Comment by rami3l** [comment]
@AndydeCleyre Sorry, this is not possible in the current version yet since it depends on `sudo -S` which `doas` lacks. Do you have a specific use case in mind?

**Comment by AndydeCleyre** [comment]
Oh, it's just that I work on systems and containers that don't usually have `sudo` installed or configured, while I do usually already have `doas` installed and configured, and would have liked to take advantage of this feature. But it's not a big deal and maybe I'll wrap it in a shell script that invokes doas for certain arguments. Thanks for the answer!

You're right that the common `doas` implementations don't support that, and that folks needing that behavior resort to using `expect`.

**Comment by rami3l** [comment]
> But it's not a big deal and maybe I'll wrap it in a shell script that invokes doas for certain arguments.

I could possibly make `sudo -S` replaceable with something else with the config (env var + cli args + config file). This might also help Windows users who want to do `gsudo`.

@AndydeCleyre How does that sound?

**Comment by AndydeCleyre** [comment]
It sounds handy, as long as it can only be set to known values (leaving the exact args up to pacaptr) to avoid a privilege-escalation attack opportunity.
