### ISSUE TITLE
[Feature Request] Return error code to shell on error

### ISSUE THREAD

**Issue by epoweripione** [rami3l/pacaptr#25]
I using `pacaptr -Si xxx` to search remote package information.
Sometimes the package doesn't exist, when using `dnf info xxx` will return an error level of non zero, but `pacaptr -Si xxx` always return 0.
I want to detect an errorlevel if there is an error like `Error: No matching Packages to list`.
Can this program return an error level of 0 if successful and non zero if a problem is encountered?
Thanks

**Comment by rami3l** [comment]
Hi @epoweripione, thanks for your feedback!

Actually, I myself want this feature as well, so I prepared a way of doing this in the current codebase. As a result, I should be able to fix this with a rather simple patch.

Unfortunately, I have other things to focus on right now, so please be patient, and I will have a look when I have free time to work on it. Stay tuned! :)

**Comment by epoweripione** [comment]
Thanks! I am waiting for the release. :)

**Comment by epoweripione** [comment]
Great job! :)
This works perfectly now, thanks!
