### ISSUE TITLE
[Feature Request] Add more options for scoop

### ISSUE THREAD

**Issue by dragonmkww** [rami3l/pacaptr#371]
I think it would be nice if you could add a `-U` option for scoop. Of course it would be a wrapper for `scoop update`.

**Comment by rami3l** [comment]
@dragonmkww 
Thanks for your feedback!

I have a question though: IIRC `pacman -U` is used when (re)installing a package with a local package file. Does `scoop update` have the same semantics?

**Comment by dragonmkww** [comment]
I think pacman -U <package> just updates a given package, so it should be a
wrapper for scoop update <package>.

**Comment by rami3l** [comment]
@dragonmkww To update a given package, please use `-Su` instead.

Just verified on a new installation that `-U` and `-Sy` don't have the same semantics: `-U` expects indeed a package **file**.

```bash
[root@/]# pacman -U vim
loading packages...
error: 'vim': could not find or read package

[root@/]# pacman -Su vim
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Package (5)        Old Version  New Version            Net Change  Download Size

core/gpm                        1.20.7.r38.ge82d1a6-4    0.41 MiB       0.14 MiB
core/hwdata        0.358-1      0.359-1                  0.00 MiB       0.46 MiB
core/libunistring  0.9.10-3     1.0-1                    0.20 MiB       0.65 MiB
extra/vim-runtime               8.2.4827-1              32.13 MiB       6.65 MiB
extra/vim                       8.2.4827-1               4.59 MiB       2.05 MiB

Total Download Size:    9.94 MiB
Total Installed Size:  41.57 MiB
Net Upgrade Size:      37.34 MiB

:: Proceed with installation? [Y/n] ^C
```

Closing this issue as this feature request is invalid.

**Comment by dragonmkww** [comment]
pacman -Su git works fine tho :)

**Comment by dragonmkww** [comment]
Here's what happens for me:
pacman -U nvim
Error Operation `u` is unimplemented for `scoop`
