### ISSUE TITLE
[Feature Request] Implement -Qs for apt

### ISSUE THREAD

**Issue by AndydeCleyre** [rami3l/pacaptr#553]
Hello, and thanks!

I expect this is already planned, but I didn't see a tracking issue, just the current compatibility table confirming that installed packages can't yet be searched (`qs` in the table), using `apt`.

**Comment by rami3l** [comment]
@AndydeCleyre Many thanks for the ping!

`-Qs` does seem to be a forgotten command in `pacaptr`'s migration to `apt` since there's still no direct equivalent of it there.

However, I should be able to make an addition real quick using `dpkg -l`. Stay tuned!
