### ISSUE TITLE
[Feature Request] Support `cargo binstall` for release artifacts

### ISSUE THREAD

**Issue by bb010g** [rami3l/pacaptr#652]
pacaptr currently publishes pre-built artifacts with each release, but `cargo binstall` isn't aware of these artifacts, making `cargo binstall pacaptr` fail. See <https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md>.

You can implement support via `[package.metadata.binstall]` keys in the crate manifest or via changing the artifact file name scheme to something `cargo binstall` will auto-detect. To see everything currently tried, try `cargo binstall --log-level debug pacaptr`. Specifying artifacts in the crate manifest should be preferred, as auto-detection requires querying the GitHub API about each tested artifact filename.

**Comment by rami3l** [comment]
@bb010g Thanks for filing this issue! I'll definitely have a closer look when I'm available.

**Comment by rami3l** [comment]
@bb010g I have made the required changes, but I'm not sure if this will work correctly.

Would you mind reviewing my changes in #653 and, if possible, test the new manifest with something like the following?

```sh
cargo binstall pacaptr --manifest-path ./Cargo.toml --dry-run --log-level=debug
```

Many thanks!
